# Generated by Django 5.0.14 on 2025-06-09 14:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_challenges_input', models.TextField(blank=True, help_text="User's input regarding daily challenges.")),
                ('goals_input', models.TextField(blank=True, help_text="User's input regarding their goals.")),
                ('ai_generated_persona_summary', models.TextField(blank=True, help_text="AI-generated summary of the user's persona based on inputs.")),
                ('ai_personality_traits', models.TextField(blank=True, help_text='AI-generated description of personality traits (e.g., JSON, or simple text).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(help_text='The user associated with this persona.', on_delete=django.db.models.deletion.CASCADE, related_name='persona', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Brief title of the task.', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the task.')),
                ('due_date', models.DateTimeField(blank=True, help_text='Optional due date and time for the task.', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', help_text='Current status of the task.', max_length=20)),
                ('ai_suggested_priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', help_text='AI-suggested priority for the task.', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='The user who owns this task.', on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['due_date', 'ai_suggested_priority'],
            },
        ),
    ]
