# Generated by Django 5.0.14 on 2025-06-09 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='persona',
            options={'ordering': ['-created_at']},
        ),
    ]
